.TH k_nn_disc 1


.SH プログラム名
k_nn_disc - k近隣法を構成しテストサンプルの識別をする


.SH 使い方
k_nn_disc <trfile> <tsfile> [-c (num)] [-tr (n1)...(nC)] [-te (n1)...(nC)] (-k (num)) (-o / -tf)


.SH オプション
.TP
.br
.B
<trfile>:
使用する訓練データのファイル名を指定して下さい。この引数は最初でなければなりません。
.TP
.br
.B
<tsfile>:
使用する検査データのファイル名を指定して下さい。この引数は2番目でなければなりません。
.TP
.br
.B
-c (num):
クラス数を指定して下さい。
.TP
.br
.B
-tr (n1)...(nC):
各クラス毎に、訓練サンプル数を指定して下さい。
.TP
.br
.B
-te (n1)...(nC):
各クラス毎に、検査サンプルの個数を指定して下さい。
.TP
.br
.B
-k (num):
k近隣の個数を決定することができます。このオプションが省略されると、最近隣法(k=1)が実行されます。
.TP
.br
.B
-o / -tf:
-oが指定された場合には検査サンプルがそれぞれどのクラスに割り当てられたかも出力します。OUT (数字)という形式で出力します。-tfが指定された場合には検査サンプルがそれぞれ正しく判定されたかを出力します。TF (数字)という形式で出力し、0は間違い、1は正解を表します。



.SH 実行例
例えば、最近隣法(k=1)を使用して検査サンプルを識別します。次元数は入力する必要がなく、自動判定されます。クラス数2で訓練サンプル数がそれぞれ100ずつ、検査サンプルがそれぞれ5ずつで、ファイル名がそれぞれex_trn、ex_tstである場合、以下の通りです。

.br
% k_nn_disc ex_trn ex_tst -tr 100 100 -te 5 5 -k 1 -c 2 -o



.SH 出力
出力は標準出力(stdout)に出力されます。以下は出力例です。

.br
   :
.br
   :
.br
OUT  1   <---  -oオプションを指定したときに出力。
.br
OUT  1         -tfオプションを指定した時には、OUTではなく
.br
OUT  1         TFというタグが付く。
.br
OUT  0
.br
OUT  1
.br
OUT  0
.br
OUT  1
.br
OUT  1
.br

.br
                (( Discrimination Result ))
.br

.br
in\\out | [  1]   [  2]   <--- 識別結果の表(confisuion
.br
------------------------       matrix)を出力する。
.br
[  1]  |    2       2
.br
[  2]  |    2       4
.br

.br
=> Recognition rate is 60.000000
.br
MULOUT    6 of   10       <--- 検査サンプルを正しく
.br
                               識別できた個数を出力。
.br


.br
Discrimination Rateの行の括弧内の数字が識別率です。-oオプションを付けたときには、検査サンプルを順番に識別する際に判定クラスも出力します。上記の例は-oオプションをつけた時の出力です。一方、-tfオプションをつけた場合には、検査サンプルを識別する際に判定クラスが検査サンプルのクラスラベルと一致すれば1、それ以外は0を出力します。その際、TFというタグと一緒に出力されます。また、検査サンプルの結果を集計したものを、(( Discrimination Result ))の行より下に行列の形で出力します。-oまたは-tfオプションが指定されていない時は、この行から出力されます。


.SH 注意事項
このプログラムは、訓練データと検査データの両方が必要です。cross validationを行う場合には、\fBcv_method\fRを使用して下さい。\fBcv_method\fRスクリプトと連動させる時には、一番最後のMULOUTと書かれた行の数字と識別結果の表(confusion matrix)が必要になります。
