.TH contour 1


.SH プログラム名
contour - 格子点毎に推定した確率密度から等高線を求める(2次元データのみ対応)


.SH 使い方
contour <file> <step> <level>


.SH オプション
.TP
.br
.B
<file>:
データと確率密度が保存されているファイルを指定して下さい。この引数は最初でなければなりません。
.TP
.br
.B
<step>:
格子点を求めた際の分割数を指定して下さい。この引数は2番目でなければなりません。
.TP
.br
.B
<level>:
等高線の分割数を指定して下さい。


.SH 与えるデータの形式
<file>のデータ形式は、(格子点データ) + (確率密度) が基本です。以下に例を示します。

.br
1.032709 2.566566 0.187119
.br
1.339661 0.951961 0.140442
.br
-0.482271 1.816928 0.037936
.br
1.197956 2.202925 0.208103
.br
1.254336 2.718007 0.182953

.br
左から順に、各格子点の1次元目、2次元目のデータ、最後に推定した確率密度となっています。


.SH 実行例
例えば、格子点を各軸毎に100分割して求めたデータと各格子点毎の密度関数の推定値が含まれているファイルを test.dat とします。また、等高線を10分割して求めるとします。このときの実行例は以下のようになります。

% contour test.dat 100 10


.SH 出力
結果は各等高線毎にデータ点がファイルが出力されます。上記の例では等高線の分割数が10なので、level1.datからlevel10.datというファイルに、各等高線毎の点が保存されています。数字の小さい方が低い等高線になります。
