.TH detect_fi 1


.SH プログラム名
detect_fi - 評価関数の値から閾値に対する特徴集合を決定する(特徴の番号順にソートして出力)


.SH 使い方
detect_fi <file> [-d (num) / -r (ratio)]


.SH オプション
.TP
.br
.B
<file>:
特徴数と評価関数の値が保存されているファイル名を指定する。
.TP
.br
.B
-d (num) / -r (num):
-dを指定した時、評価関数の値が大きい特徴から順にnum個取った特徴集合を出力する。-rを指定すると、評価関数の最大値からnum%差し引いた値に対応する(最も近い)評価関数の値をもつ特徴集合を出力する。
