.TH dinfo_reader 1


.SH プログラム名
dinfo_reader - データの情報ファイルからクラス数、特徴数、サンプル数を得る


.SH データの情報を保存するファイル
使用するデータに関して情報をファイルに保存しておきます。形式は以下の通りです。

.br
# (データ名)
.br
class : (num)
.br
feature : (num)
.br
sample : (n1)...(nC)

.br
クラス数、特徴数、サンプル数を並べる順番は特にありません。但し、先頭が# (データ名)で始まり、その下に3つの情報を書いて下さい。また、区切りには空白、またはタブを使用して下さい。空白、タブの個数に関して特に指定はありません。一つのファイルに複数のデータに関する情報を保存することもできます。以下がその例です。

.br
# fried100.trn
.br
class : 2
.br
feature : 10
.br
sample : 50 50
.br

.br
# wave100.trn
.br
class : 3
.br
feature : 40
.br
sample : 40 38 22
.br

.br
# sonar.trn
.br
class : 2
.br
feature : 60
.br
sample : 97 111
.br

.SH 注意事項
このプログラムは他のいろいろなプログラムから呼び出されます。形式は必ず守って下さい。形式が異なると、他のプログラムが正しく動作しない可能性があります。
