.TH eigen 1


.SH プログラム名
eigen - ヘッセンベルグQR法による固有値計算


.SH 使い方
eigen <file> 


.SH オプション
.TP
.br
.B
<file>:
使用するデータのファイル名を指定して下さい。この引数は最初でなければなりません。このファイルには、ターゲットとなる行列のデータを含んでください。

.SH 実行例と行列の形式
例えば、3×3の大きさで以下の行列に対して固有値を計算するとします。

.br
4       -3      1
.br
-2      5       3
.br
2       -3      1

.br
行列のデータ形式は、(1)要素を最低1文字分の空白またはタブで区切る、(2)各行の最後は改行する、の2点のみ注意してください。この行列をtest.matrixというファイルに保存してある場合、以下のようにして使用します。

.br
% eigen test.matrix

.SH 出力
計算結果は、以下のようになります。

.br
5.414 + 0.000 i 
.br
2.586 + 0.000 i 
.br
2.000 + 0.000 i 

.br
固有値は、a+b\fBi\fR(a,bは実数、\fBi\fRは虚数単位)の形式で出力されます。
