.TH file_split 1


.SH プログラム名
file_split - ファイルにあるデータを分割する


.SH 使い方
file_split <file> [-s (k) (n1)...(nk) / -q (num)] (-o (str))


.SH 説明
.PP
.B file_split
はファイルにあるデータをオプションにより指定された方法で分割します。file_splitでは行単位でデータを扱います。ファイルをバイト単位で分割する場合には、\fBsplit\fRを使用して下さい。


.SH オプション
.TP
.br
.B
<file>:
データのファイル名を指定して下さい。
.TP
.br
.B
-s (k) (n1)...(nk) / -q:
-sオプションを指定すると、先頭から順番に(n1)個、...、(nk)個のk個のデータに分割し、分割したデータ毎にファイルに出力します。-qオプションを指定すると、出来るだけ均等に(num)分割し、ファイルに出力します。
.TP
.br
.B
-o (str):
出力するファイルの名前を指定することができます。正確には、このオプションで指定したファイル名にindexが付いたファイルに出力されます。特に指定がなければ、元のファイル名にindexを付けた名前を使用します。


.SH 注意事項
.PP
-sオプションを指定した場合、それぞれの分割された行数の合計が元のファイルの行数と一致していなければなりません。例えば、データが100行あるファイルを10、30、60(合計100)と分割することはできますが、10、10、10(合計30)と分割することはできません。


.SH 実行例
使用するファイル名がexample.datで、データが100行あるとします。example.datを3分割するには、以下のように使用します。

.br
% file_split example.dat -q 3

.br
実行後、example.dat_1 example.dat_2 example.dat_3というファイルが作成され、データはそれぞれのファイルに34、33、33行含まれています。もし、出力するファイル名をClassとするのであれば、-oオプションを付けて実行して下さい。

.br
% file_split example.dat -q 3 -o Class

.br
また、決められた数で分割する場合には、以下のように使用します。

.br
% file_split example.dat -s 3 10 30 60
