.TH gen_rate_fs_fig 1


.SH プログラム名
gen_rate_fs_fig - 特徴数と識別率のグラフを作成する


.SH 使い方
gen_rate_fs_fig <name> <dinfo> <cinfo> (-from (num)) (-to (num))


.SH オプション
.TP
.br
.B
<name>:
データの名前を指定する。
.TP
.br
.B
<dinfo>:
データの情報を記述したファイルを指定する。
.TP
.br
.B
<cinfo>:
識別率の計算に用いた識別子の情報ファイルを指定する。
.TP
.br
.B
-from (num):
識別率の軸(y軸)の最小値を指定する。
.TP
.br
.B
-to (num):
識別率の軸(y軸)の最大値を指定する。
