.TH histo 1


.SH プログラム名
histo - ヒストグラムを求める


.SH 使い方
histo <file> [-step (num)]


.SH 説明
.PP
.B histo
は、与えられたデータに対してヒストグラムを求めます。データに対して最大値と最小値を自動判定し、階級毎に個数を調べていきます。階級の幅はオプションによりしていできます。


.SH オプション
.TP
.br
.B
<file>:
使用するデータのファイル名を指定して下さい。
.TP
.br
.B
-step (num):
階級の幅を指定して下さい。


.SH 出力
プログラムを実行すると、以下のような結果が標準出力(\fBstdout\fR)に出力されます。

.br
 -10.00 -->   -8.00 [   -9.00 ]     0
.br
  -8.00 -->   -6.00 [   -7.00 ]     0
.br
  -6.00 -->   -4.00 [   -5.00 ]     1
.br
  -4.00 -->   -2.00 [   -3.00 ]   478
.br
  -2.00 -->   +0.00 [   -1.00 ]  9467
.br
  +0.00 -->   +2.00 [   +1.00 ]  9585
.br
  +2.00 -->   +4.00 [   +3.00 ]   469
.br
  +4.00 -->   +6.00 [   +5.00 ]     1
.br
  +6.00 -->   +8.00 [   +7.00 ]     0
.br
  +8.00 -->  +10.00 [   +9.00 ]     0

.br
出力は左から順に、各階級の最小値、最大値、階級値、そして個数となります。この結果をファイルに保存し、\fBgnuplot\fRにて以下のコマンドを実行すると、ヒストグラムの図が出力されます。例えば、結果をtest.datに保存した場合には、gnuplotを起動した後、以下を実行します。

.br
plot 'test.dat' using 5:7 with histeps
