.TH invmat 1


.SH プログラム名
invmat - Gauss-Jordan法による逆行列計算


.SH 使い方
invmat <file> 


.SH オプション
.TP
.br
.B
<file>:
使用するデータのファイル名を指定して下さい。この引数は最初でなければなりません。このファイルには、ターゲットとなる行列のデータを含んでください。


.SH 実行例と行列の形式
例えば、3×3の大きさで以下の行列に対して固有値を計算するとします。

.br
1  3  3
.br
1  3  4
.br
2  4  3

.br
行列のデータ形式は、(1)要素を最低1文字分の空白またはタブで区切る、(2)各行の最後は改行する、の2点のみ注意してください。この行列をtest.matrixというファイルに保存してある場合、以下のようにして使用します。

.br
% invmat test.matrix

.SH 出力
計算結果は、以下のようになります。

.br
-3.500 1.500 1.500
.br
2.500 -1.500 -0.500
.br
-1.000 1.000 0.000


.SH 注意事項
行列のランクが落ち、手で計算するのが困難な場合には、計算が正しくないことがあります。例えば、3×3の行列の場合、特性方程式の解が3重解になるときです。
