.TH minmax 1


.SH プログラム名
minmax - データの最大値と最小値をみつける


.SH 使い方
minmax <file1> (-all)


.SH オプション
.TP
.br
.B
<file>:
データが保存されているファイル名を指定して下さい。
.TP
.br
.B
-all:
このオプションを指定すると、次元毎ではなく全ての次元の中での最大値と最小値を求めます。


.SH 出力
結果は標準出力に表示されます。-allを指定しない場合には、次元毎の最大値と最小値が出力されます。以下がその例です。

.br
-3.113756 3.611450
.br
-3.658260 3.678289
.br
-3.693167 3.710289
.br
-3.645339 3.752001
.br
-2.079340 2.299781
.br
-3.166968 2.512790
.br
-2.737669 2.583692
.br
-2.513489 2.426908
.br
-2.163659 3.376684
.br
-2.449602 2.258556

.br
上記の例は10次元データの例です。一番上から1次元目の最小値、最大値が順に並んでいます。左側が最小値で右側が最大値です。-allを指定すると、全ての次元の中での最小値と最大値を出力します。つまり、3次元目の最小値と4次元目の最大値が出力されます。以下が出力例です。

.br
-3.693167 3.752001
