.TH rotate_fig 1


.SH プログラム名
rotate_fig - 多次元データを3次元データに変換し回転させながら眺める


.SH 使い方
rotate_fig <file> [-c (num)] [-tr (n1)...(nC)] (-step (num))


.SH オプション
.TP
.br
.B
<file>:
使用するデータのファイル名を指定して下さい。この引数は最初でなければなりません。
.TP
.br
.B
-c (num):
使用するデータのクラス数を指定して下さい。
.TP
.br
.B
-tr (n1)...(nC):
使用するデータのクラス毎のサンプル数を指定して下さい。
.TP
.br
.B
-step (num):
回転させる角度を指定することができます。このオプションが省略されれば1度ずつ回転します。任意の角度を入力できますが、角度が小さ過ぎると表示するまでに時間がかかり、場合によってはディスクの空き容量がなくなるかもしてません。理由は、それぞれの角度の状態をポストスクリプト形式で保存しているからです。


.SH 実行例
使用するデータがexample.datで、データの情報が書かれたファイルがdata.txtである場合、以下のように使用します。

.br
% rotate_fig example.dat -c 2 -tr 100 100

.br
上記の例では、クラス数が2で各クラスともにサンプル数は100の場合です。また、ゆっくり表示させたい場合には、ステップ数を細かくすれば可能です。

.br
% rotate_fig example.dat data -c 2 -tr 100 100 -step 0.1

.br
但し、stepを小さくすると図を表示するまでに時間がかかります。


.SH 出力
gnuplotが自動的に起動し、3次元グラフを回転させながら表示します。
