.TH roundoff 1


.SH プログラム名
roundoff - 四捨五入した値を返す


.SH 使い方
roundoff <value> <position>


.SH オプション
.TP
.br
.B
<value>:
値(実数)を指定して下さい。
.TP
.br
.B
<position>:
四捨五入する位を10^xのxの値で指定して下さい。100の位であればpos=2、小数第一位であればpos=-1と指定して下さい。


.SH 実行例
12345.6789を1000の位で四捨五入するには以下のように実行します。

.br
% roundoff 12345.6789 3

.br
12345.6789を小数第4位で四捨五入するには以下のように実行します。

.br
% roundoff 12345.6789 -4


.SH 注意事項
1の位で四捨五入する時はpos=0となります。


.SH 出力
結果は標準出力に四捨五入した値を出力します。
