.TH shuffle 1


.SH プログラム名
shuffle - データをランダムに並び換える


.SH 使い方
shuffle <file> (-s seed)


.SH オプション
.TP
.br
.B
<file>:
データのファイル名を指定して下さい。
.TP
.br
.B
(-s seed):
乱数を用いてデータを並び換える際の乱数の種を指定することができます。乱数の種を指定することで、一定の規則でデータを並び換えることができます。


.SH 実行例
このプログラムは標準出力に出力されます。ファイルに保存する場合には、例えばout.datというファイルに出力する場合には、

.br
% shuffle test.dat > out.dat

.br
と使用して下さい。尚、データの出力形式は処理のフォーマットです。
