.TH syori_to_c45 1


.SH プログラム名
syori_to_c45 - 処理フォーマットからC4.5のプログラムのデータ形式に変換


.SH 使い方
syori_to_c45 <file> <data / test> <class> <n1> <n2> ... <nC>


.SH オプション
.TP
.br
.B
<file>:
データのファイル名を指定する。
.TP
.br
.B
<data / test>:
作成するデータの種類を指定する。訓練データの場合はdata、検査データの場合はtestを指定する。
.TP
.br
.B
<class>:
クラス数を指定する。
.TP
.br
.B
<n1>...<nC>:
各クラスのサンプル数を指定する。先頭から順にクラス1、2、...のサンプル数となるように指定する。
