.TH transmat 1


.SH プログラム名
transmat - 転置行列を求める簡易プログラム


.SH 使い方
transmat <file>


.SH オプション
.TP
.br
.B
<file>:
行列が保存されているファイル名を指定して下さい。

.SH 実行例と行列の形式
例えば、2×3の大きさの行列は以下のようになります。

.br
 4     -3      1
.br
-2      5      3

.br
行列のデータ形式は、(1)要素を最低1文字分の空白またはタブで区切る、(2)各行の最後は改行する、の2点のみ注意してください。また、行列をtest_matrixというファイルに保存してある場合、以下のようにして使用します。

.br
% transmat test_matrix


.SH 出力
計算結果は、以下のようになります。

.br
 4.000 -2.000
.br
-3.000  5.000
.br
 1.000  3.000

.br
結果は標準出力に表示されます。
