.TH vecarg 1


.SH プログラム名
vecarg - 二つのベクトルの角度を計算する


.SH 使い方
vecarg <file1> <file2> (-rad)


.SH オプション
.TP
.br
.B
<file1> <file2>:
行列が保存されているファイル名を指定して下さい。
.TP
.br
.B
-rad:
このオプションを指定すると、ラジアン単位の角度を0度から180度の範囲で出力します。特に指定されない場合には、cosの値(-1から1の範囲)を出力します。


.SH 実行例とベクトルの形式
例えば、各ファイルにそれぞれ2次元のベクトルが以下のように保存されているとします。

.br
 1.0 0.0              1.0 0.0
.br
 0.0 1.0              1.0 0.0
.br
-1.0 0.0              1.0 0.0
.br
 <file1>              <file2>

.br
ベクトルの形式は、(1)要素を最低1文字分の空白またはタブで区切る、(2)各行の最後は改行する、の2点のみ注意してください。ベクトルの各要素がファイル内で縦にきれいに並んでいる必要はありません。上記の例ではfile1にある3つのベクトルがそれぞれx軸から何度ずれているかを計算する例です。二つのベクトルを保存しているファイルををtest1、test2というファイルに保存してある場合、以下のようにして使用します。
		
.br
% vecarg test1 test2

.SH 出力


計算結果は標準出力に表示されます。-radを指定しない場合には、cosの値が-1から1の範囲で出力されます。以下が上記の例に対する出力例です。

.br
1.000000
.br
0.000000
.br
-1.000000

.br
-radを指定すると、ラジアン単位の角度が出力されます。以下が出力例です。

.br
0.000000
.br
1.570796
.br
3.141593
